"""CLI entrypoint for the modular PageIndex SEC pipeline."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .pipeline import run_pipeline


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="PageIndex-native recursive tree-search pipeline for SEC 10-K.")
    parser.add_argument(
        "--sections-json",
        default="data/ingestion/sec/extracted_10k_sections.json",
        help="Input JSON generated by the SEC extraction step in ingestion.sec_edgar",
    )
    parser.add_argument(
        "--docs-dir",
        default="src/pageindex/pageindex_docs",
        help="Generated markdown docs directory",
    )
    parser.add_argument(
        "--workspace",
        default="src/pageindex/pageindex_workspace",
        help="PageIndex workspace directory",
    )
    parser.add_argument(
        "--output-dir",
        default="src/pageindex/pageindex_rag_output",
        help="Output artifacts directory",
    )
    parser.add_argument("--question", default=None, help="Optional question for routed recursive retrieval")
    parser.add_argument("--openai-model", default="gpt-4.1-mini", help="LLM model for routing/search/answer")
    parser.add_argument("--index-model", default=None, help="Optional indexing model override")
    parser.add_argument("--retrieve-model", default=None, help="Optional retrieve model override")
    parser.add_argument("--index-mode", default="md", choices=["auto", "md", "pdf"], help="PageIndex index mode")
    parser.add_argument("--reindex", action="store_true", help="Force re-indexing even if docs already exist")
    parser.add_argument("--docs-only", action="store_true", help="Only generate markdown docs")
    parser.add_argument("--max-context-chars", type=int, default=30000, help="Max chars in final answer context")
    parser.add_argument("--max-docs", type=int, default=2, help="Max routed docs")
    parser.add_argument("--max-depth", type=int, default=4, help="Recursive tree search depth cap")
    parser.add_argument("--max-nodes-per-level", type=int, default=3, help="Node picks per depth")
    parser.add_argument("--max-candidate-nodes", type=int, default=20, help="Candidates per depth before LLM pick")
    return parser.parse_args()


def main() -> None:
    """Run CLI pipeline and print summary JSON."""
    args = parse_args()
    summary = run_pipeline(
        sections_json_path=Path(args.sections_json),
        docs_dir=Path(args.docs_dir),
        workspace=Path(args.workspace),
        output_dir=Path(args.output_dir),
        question=args.question,
        openai_model=args.openai_model,
        index_model=args.index_model,
        retrieve_model=args.retrieve_model,
        reindex=args.reindex,
        docs_only=args.docs_only,
        max_context_chars=args.max_context_chars,
        index_mode=args.index_mode,
        max_docs=args.max_docs,
        max_depth=args.max_depth,
        max_nodes_per_level=args.max_nodes_per_level,
        max_candidate_nodes=args.max_candidate_nodes,
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
