from __future__ import annotations

SOURCE_TABLE_DDLS = {
    "source_ofac_sdn_entities": """
        CREATE TABLE IF NOT EXISTS source_ofac_sdn_entities (
            tenant_id TEXT NOT NULL,
            source_entity_id TEXT NOT NULL,
            primary_name TEXT NOT NULL,
            entity_type TEXT,
            source_list_name TEXT,
            sanctions_programs TEXT,
            sanctions_type TEXT,
            date_published DATE,
            aliases TEXT,
            alias_count INTEGER,
            date_of_birth DATE,
            place_of_birth TEXT,
            nationality TEXT,
            citizenship TEXT,
            gender TEXT,
            address_text TEXT,
            address_count INTEGER,
            document_ids TEXT,
            source_file_name TEXT NOT NULL,
            source_loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            raw_payload JSONB NOT NULL,
            PRIMARY KEY (tenant_id, source_entity_id)
        )
    """,
    "source_comtrade_flows": """
        CREATE TABLE IF NOT EXISTS source_comtrade_flows (
            tenant_id TEXT NOT NULL,
            source_record_hash TEXT NOT NULL,
            type_code TEXT,
            freq_code TEXT,
            ref_period_id BIGINT,
            ref_year INTEGER NOT NULL,
            ref_month INTEGER,
            period TEXT,
            reporter_code INTEGER,
            flow_code TEXT,
            flow_desc TEXT,
            reporter_iso TEXT,
            reporter_desc TEXT,
            partner_code INTEGER,
            partner_iso TEXT,
            partner_desc TEXT,
            partner2_code INTEGER,
            partner2_iso TEXT,
            partner2_desc TEXT,
            classification_code TEXT,
            classification_search_code TEXT,
            is_original_classification BOOLEAN,
            cmd_code TEXT,
            cmd_code_level2 TEXT,
            cmd_code_level4 TEXT,
            cmd_code_level6 TEXT,
            cmd_desc TEXT,
            aggr_level INTEGER,
            is_leaf BOOLEAN,
            customs_code TEXT,
            customs_desc TEXT,
            mos_code TEXT,
            mot_code INTEGER,
            mot_desc TEXT,
            qty_unit_code INTEGER,
            qty_unit_abbr TEXT,
            qty DOUBLE PRECISION,
            is_qty_estimated BOOLEAN,
            alt_qty_unit_code INTEGER,
            alt_qty_unit_abbr TEXT,
            alt_qty DOUBLE PRECISION,
            is_alt_qty_estimated BOOLEAN,
            net_wgt DOUBLE PRECISION,
            is_net_wgt_estimated BOOLEAN,
            gross_wgt DOUBLE PRECISION,
            is_gross_wgt_estimated BOOLEAN,
            cifvalue DOUBLE PRECISION,
            fobvalue DOUBLE PRECISION,
            primary_value DOUBLE PRECISION,
            legacy_estimation_flag INTEGER,
            is_reported BOOLEAN,
            is_aggregate BOOLEAN,
            source_file_name TEXT NOT NULL,
            source_loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            raw_payload JSONB NOT NULL,
            PRIMARY KEY (tenant_id, source_record_hash)
        )
    """,
    "source_noaa_storm_events": """
        CREATE TABLE IF NOT EXISTS source_noaa_storm_events (
            tenant_id TEXT NOT NULL,
            begin_yearmonth INTEGER,
            begin_day INTEGER,
            begin_time INTEGER,
            end_yearmonth INTEGER,
            end_day INTEGER,
            end_time INTEGER,
            event_id BIGINT NOT NULL,
            episode_id BIGINT,
            state TEXT,
            state_fips INTEGER,
            year INTEGER,
            month_name TEXT,
            event_type TEXT,
            cz_type TEXT,
            cz_fips INTEGER,
            cz_name TEXT,
            wfo TEXT,
            begin_date_time TIMESTAMP,
            cz_timezone TEXT,
            end_date_time TIMESTAMP,
            injuries_direct INTEGER,
            injuries_indirect INTEGER,
            deaths_direct INTEGER,
            deaths_indirect INTEGER,
            damage_property_raw TEXT,
            damage_property_usd DOUBLE PRECISION,
            damage_crops_raw TEXT,
            damage_crops_usd DOUBLE PRECISION,
            source TEXT,
            magnitude DOUBLE PRECISION,
            magnitude_type TEXT,
            flood_cause TEXT,
            category TEXT,
            tor_f_scale TEXT,
            tor_length DOUBLE PRECISION,
            tor_width DOUBLE PRECISION,
            tor_other_wfo TEXT,
            tor_other_cz_state TEXT,
            tor_other_cz_fips INTEGER,
            tor_other_cz_name TEXT,
            begin_range DOUBLE PRECISION,
            begin_azimuth TEXT,
            begin_location TEXT,
            end_range DOUBLE PRECISION,
            end_azimuth TEXT,
            end_location TEXT,
            begin_lat DOUBLE PRECISION,
            begin_lon DOUBLE PRECISION,
            end_lat DOUBLE PRECISION,
            end_lon DOUBLE PRECISION,
            event_mid_lat DOUBLE PRECISION,
            event_mid_lon DOUBLE PRECISION,
            episode_narrative TEXT,
            event_narrative TEXT,
            data_source TEXT,
            source_file_name TEXT NOT NULL,
            source_loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            raw_payload JSONB NOT NULL,
            PRIMARY KEY (tenant_id, event_id)
        )
    """,
    "source_fda_warning_letters": """
        CREATE TABLE IF NOT EXISTS source_fda_warning_letters (
            tenant_id TEXT NOT NULL,
            source_record_hash TEXT NOT NULL,
            posted_date DATE,
            letter_issue_date DATE,
            company_name TEXT NOT NULL,
            company_name_normalized TEXT,
            issuing_office TEXT,
            subject TEXT,
            risk_category TEXT,
            severity TEXT,
            response_letter TEXT,
            closeout_letter TEXT,
            source_file_name TEXT NOT NULL,
            source_loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            raw_payload JSONB NOT NULL,
            PRIMARY KEY (tenant_id, source_record_hash)
        )
    """,
}

SOURCE_TABLE_NAMES = tuple(SOURCE_TABLE_DDLS.keys())


def ensure_source_tables(conn) -> None:
    with conn.cursor() as cur:
        for ddl in SOURCE_TABLE_DDLS.values():
            cur.execute(ddl)


def drop_source_tables(conn) -> None:
    with conn.cursor() as cur:
        for table_name in reversed(SOURCE_TABLE_NAMES):
            cur.execute(f"DROP TABLE IF EXISTS {table_name}")


